### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by ghost** [TeamMetallurgy/MetallurgyChisel#2]
Minecraft is crashing when attempting to initialize this mod.  The error message is as follows:

```
[08:40:28] [Client thread/ERROR]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[08:40:28] [Client thread/ERROR]: 
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
    UCH Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
    UCH CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
    UCH MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
    UCH NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
    UCH OpenComputers|Core{1.5.18.36} [OpenComputers (Core)] (minecraft.jar) 
    UCH OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
    UCH SomniaCore{1.3.1.1} [SomniaCore] (minecraft.jar) 
    UCH OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCH <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
    UCH sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.5.1.jar) 
    UCH CustomOreGen{1.2.24} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.24.jar) 
    UCH Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    UCH HardLib{9.16.0a} [HardLib] (1.7.10-HardLib-9.16.0a.jar) 
    UCH HarderWildlife{9.16.0a} [Harder Wildlife] (1.7.10-HarderWildlife-9.16.0a.jar) 
    UCH battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar) 
    UCH OreFlowers{1.0.0} [Ore Flowers] (1.7.10-OreFlowers-2.0.0.jar) 
    UCH bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCH StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
    UCH CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCH advancedgenetics{1.5.9} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.9.jar) 
    UCH AgriCraft{1.7.10-1.4.0} [AgriCraft] (AgriCraft-1.7.10-1.4.0-1.7.10.jar) 
    UCH antiqueatlas{4.2.7-1.7.10} [Antique Atlas] (antiqueatlas-4.2.7-1.7.10.jar) 
    UCH AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
    UCH bdlib{1.9.3.107} [BD Lib] (bdlib-1.9.3.107-mc1.7.10.jar) 
    UCH betterboat{1.0.0} [Better Boat] (BetterBoat-1.7.10-1.0.0.jar) 
    UCH betterstorage{0.13.1.126} [BetterStorage] (BetterStorage-1.7.10-0.13.1.126.jar) 
    UCH BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
    UCH BlockProperties{0.1.2} [Block Properties] (BlockProperties-1.7.10-0.1.2.jar) 
    UCH BuildCraft|Core{7.1.6} [BuildCraft] (buildcraft-7.1.6-core.jar) 
    UCH BuildCraft|Builders{7.1.6} [BC Builders] (buildcraft-7.1.6-builders.jar) 
    UCH BuildCraft|Energy{7.1.6} [BC Energy] (buildcraft-7.1.6-energy.jar) 
    UCH CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCH Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
    UCH ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCH chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
    UCH Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
    UCH chiseltones{@VERSION@} [Chisel Tones] (ChiselTones-1.7.10-1.0-3.jar) 
    UCH cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
    UCH BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
    UCH CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
    UCH CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
    UCH ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
    UCH ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
    UCH customitems{1.0.9b} [Meta Mod: Custom Items] (customitems-1.0.9_beta_1.7.10.jar) 
    UCH PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.1.1_1.7.10.jar) 
    UCH props{2.1.1} [Decocraft] (Decocraft-2.1.1_1.7.10.jar) 
    UCH Forestry{3.6.10.1} [Forestry for Minecraft] (forestry_1.7.10-3.6.10.1.jar) 
    UCH MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
    UCH ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
    UCH minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
    UCH DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V9b.jar) 
    UCH DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
    UCH DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
    UCH DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
    UCH DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
    UCH DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
    UCH DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
    UCH DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
    UCH DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
    UCH DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
    UCH DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
    UCH RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V9b.jar) 
    UCH ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V9b.jar) 
    UCH eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCH endercore{1.7.10-0.1.0.24_beta} [EnderCore] (EnderCore-1.7.10-0.1.0.24_beta.jar) 
    UCH EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) 
    UCH enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
    UCH ExpandedRedstone{1.0} [Expanded Redstone] (ExpandedRedstone 1.7.10 V9a.jar) 
    UCH extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar) 
    UCH ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
    UCH fossil{1.7.10 Build 7.2.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.jar) 
    UCH GardenCore{1.7.10-1.6.3} [Garden Core] (GardenStuff-1.7.10-1.6.3.jar) 
    UCH GardenContainers{1.7.10-1.6.3} [Garden Containers] (GardenStuff-1.7.10-1.6.3.jar) 
    UCH GardenStuff{1.7.10-1.6.3} [Garden Stuff] (GardenStuff-1.7.10-1.6.3.jar) 
    UCH GardenTrees{1.7.10-1.6.3} [Garden Trees] (GardenStuff-1.7.10-1.6.3.jar) 
    UCH gendustry{1.6.1.126} [GenDustry] (gendustry-1.6.1.126-mc1.7.10.jar) 
    UCH HungerInPeace{1.0.0} [Hunger In Peace] (HungerInPeace-mc1.7.10-1.0.0.jar) 
    UCH iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
    UCH mod_Invasion{1.1.2} [Invasion] (Invasion_1.1.3_1.7.10.jar) 
    UCH inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
    UCH JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
    UCH journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCH Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
    UCH MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
    UCH Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
    UCE metallurgychisel{1.0.0.11} [Metallurgy Chisel] (MetallurgyChisel-1.7.10-1.0.0.11.jar) 
    UCH MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) 
    UCH MobProperties{0.4.1} [Mob Properties] (MobProperties-1.7.10-0.4.2.jar) 
    UCH modtweaker2{0.9.2} [Mod Tweaker 2] (ModTweaker2-0.9.3.jar) 
    UCH cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
    UCH AS_MultiMine{1.4.4} [Multi Mine] (MultiMine-1.7.10.jar) 
    UCH NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
    UCH NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
    UCH NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
    UCH OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
    UCH OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
    UCH ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCH OpenComputers{1.5.18.36} [OpenComputers] (OpenComputers-MC1.7.10-1.5.18.36-universal.jar) 
    UCH harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar) 
    UCH ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
    UCH ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
    UCH ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCH ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
    UCH ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
    UCH RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
    UCH ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V9b.jar) 
    UCH RefinedRelocation{1.1.4} [Refined Relocation] (RefinedRelocation-mc1.7.10-1.1.4.jar) 
    UCH rftools{3.41} [RFTools] (rftools-3.41.jar) 
    UCH punt{1.7.10-10.13.0-16.1} [Punt] (smallboats-1.7.10-10.13.0-16.1.jar) 
    UCH whitehall{1.7.10-10.13.0-16.1} [Whitehall] (smallboats-1.7.10-10.13.0-16.1.jar) 
    UCH hoy{1.7.10-10.13.0-16.1} [Hoy] (smallboats-1.7.10-10.13.0-16.1.jar) 
    UCH smallboats{1.7.10-10.13.0-16.1} [SmallBoats (base)] (smallboats-1.7.10-10.13.0-16.1.jar) 
    UCH examplemod{1.0} [examplemod] (Somnia-1.4.3.1.jar) 
    UCH Somnia{-au} [Somnia] (Somnia-1.4.3.1.jar) 
    UCH soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
    UCH SpecialAI{1.1.1} [Special AI] (SpecialAI-1.7.10-1.1.1.jar) 
    UCH SpecialMobs{3.1.1} [Special Mobs] (SpecialMobs-1.7.10-3.1.1.jar) 
    UCH SpiceOfLife{1.2.4} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.4.jar) 
    UCH StorageDrawers{1.7.10-1.6.2} [Storage Drawers] (StorageDrawers-1.7.10-1.6.2.jar) 
    UCH StorageDrawersForestry{1.7.10-1.0.3} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.0.3.jar) 
    UCH Sync{4.0.0} [Sync] (Sync-4.0.0.jar) 
    UCH ToolUtilities{0.0.1} [Tool Utilities] (ToolUtilities-MC1.7.10-0.0.1-10.jar) 
    UCH WailaHarvestability{1.1.3} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.3.jar) 
    UCH wailaplugins{MC1.7.10-0.1.2-21} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.2-21.jar) 
    UCH woodenbucket{0.0.3.20151006160113} [Wooden Bucket] (WoodenBucket-1.7.10-0.0.3b6.jar) 
    UCH ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) 
    UCH McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCH ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
    UCH MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
    UCH RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
    UCH aobd{2.8.4} [Another One Bites The Dust] (AOBD-2.8.4.jar) 
    UCH HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
    UCH VeganOption{0.1.2} [The Vegan Option] (VeganOption-mc1.7.10-0.1.2.jar) 
    UCH ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
[08:40:28] [Client thread/ERROR]: The following problems were captured during this phase
[08:40:28] [Client thread/ERROR]: Caught exception from metallurgychisel
java.lang.NullPointerException
    at com.teammetallurgy.metallurgychisel.MetallurgyChiselBlocks.createBlocks(MetallurgyChiselBlocks.java:39) ~[MetallurgyChiselBlocks.class:?]
    at com.teammetallurgy.metallurgychisel.MetallurgyChiselBlocks.init(MetallurgyChiselBlocks.java:26) ~[MetallurgyChiselBlocks.class:?]
    at com.teammetallurgy.metallurgychisel.MetallurgyChisel.preinit(MetallurgyChisel.java:37) ~[MetallurgyChisel.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Unknown Source) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[08:40:28] [Client thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.crash.CrashReportCategory.func_85069_a(CrashReportCategory.java:145) ~[k.class:?]
    at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:333) ~[b.class:?]
    at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:303) ~[b.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) ~[Main.class:?]
    ... 14 more
[08:40:28] [Client thread/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:497)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.EntryPoint.main(EntryPoint.java:54)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Runtime.exit(Runtime.java:107)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.System.exit(System.java:971)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 8 more
[08:40:28] [Client thread/INFO]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 5
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Runtime.exit(Runtime.java:107)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.System.exit(System.java:971)
[08:40:28] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.EntryPoint.main(EntryPoint.java:58)
```

**Comment by thegreatersea** [comment]
I'd have to double-check in my instance, but do you have any metallurgy metals or metal sets disabled?

**Comment by ghost** [comment]
Ahhh, I should have mentioned that.  Yes, I do.  I have disabled fantasy, nether, and ender metals; I just needed to have base, utility, and precious metals.

**Comment by damonmensch** [comment]
I too am getting this error. It seems your mod isn't checking if a metal is disabled before attempting to create it's variations, and thus throwing a not found error.

**Comment by SynfulChaot** [comment]
This is definitely still an issue.

**Comment by chaos234** [comment]
Since that it has no configuration file it is a bit useless to change smth. in the Metallurgy.cfg until this gets fixed but since it's over one year old I think that it will never get fixed or would it get fixed soon @TeamMetallurgy ?

I also can't accept such stupied errors on an additional mod which acts like an addon for another mod but is not fully compatible with it ... to bad.

**Comment by MapperTV** [comment]
I'm running into that error as well. Disabling block categories in Metallurgy configuration will make MetallurgyChisel crash. Until this is fixed, I won't be using this mod...
